# LazyRoad config file

# Fields are the %0, %1, %2 ... values. You can reorder them and even remove if
# you want. They are optional.

# Colors, use UTF-8 !:
# &0 : BLACK
# &1 : DARK_BLUE
# &2 : DARK_GREEN
# &3 : DARK_AQUA
# &4 : DARK_RED
# &5 : DARK_PURPLE
# &6 : GOLD
# &7 : GRAY
# &8 : DARK_GRAY
# &9 : BLUE
# &a : GREEN
# &b : AQUA
# &c : RED
# &d : LIGHT_PURPLE
# &e : YELLOW
# &f : WHITE

messages:
  # errors
  noRoad: "&4There is no road with that name"
  noPillar: "&4There is no pillar with that name"
  noPermission: "&4You don't have the permission."
  ioError: "&4An error occured while performing reading/writings operations on files."
  undoError: "&4Can't undo."
  alreadyBuilding: "&4You are already building a road, stop the current road with &e/road stop&4."
  teleported: "&4Road stopped as you teleported to another world."
  # other messages
  buildStop: "&4Road Stopped, You are on the &6%0&4 block of road."
  reload: "&bLazyRoad is reloaded."
  undo: "&bUndone."
  roadCount: "&bRoad length: &e%0&b blocks."
  beginBuilding: "&bLazyRoad build mode enabled."
  straightEnabled: "&bStraight mode enabled."
  straightDisabled: "&bStraight mode disabled."
  forceUp: "&bForcing road to go up."
  forceDown: "&bForcing road to go down."
  normal: "&bRoad will be placed normally now."
  lazyminer:
    enable: "&bLazyMiner mode enabled."
    disable: "&bLazyMiner mode disabled."
    empty: "&4That's the last of it."
    notempty: "&4There's still &6%0&4 stacks of items left to put somewhere."
    drops: "&bEnable LazyMiner to run this command."
    stop: "&4You now have &6%0&4 stacks of items stored."
    addid: "&6%0&4 has been added to the blocks ids LazyMiner Mines."
    removeid: "&6%0&4 has been removed from the blocks ids LazyMiner Mines."
    cantremove: "&6%0&4 was not in the list of blocks LazyMiner Mines."
    ids: "&4Checked Ids: &6%0"
lazyminer:
  # TODO Change ids for release
  ids: [14,15,16,17,21,49,56,73,74]
